[package]
name = "opt8n"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
# Core
hashbrown.workspace = true
serde.workspace = true
tracing.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true
futures.workspace = true
color-eyre.workspace = true
tracing-subscriber.workspace = true

# CLI
clap.workspace = true
inquire = { version = "0.7.5", features = ["editor"] }
axum = "0.7"
ctrlc = "3.4"

# Alloy
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-transport = "0.2"
alloy-provider = "0.2"
alloy-transport-http = "0.2"
op-alloy-consensus.workspace = true
op-alloy-network.workspace = true

# OP Types + Kona
op-test-vectors.workspace = true
kona-primitives.workspace = true
kona-mpt.workspace = true
superchain-registry.workspace = true

# reth
reth-primitives = { workspace = true, features = ["optimism"] }
reth-evm.workspace = true
reth-evm-optimism.workspace = true
reth-chainspec.workspace = true

# revm
revm = { workspace = true, features = ["optimism", "alloydb"] }
