[book]
authors = ["refcell"]
language = "en"
multilingual = false
src = "src"
title = "OP Test Vectors"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.template]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
